name: learn-github-action
on: [push]
jobs:
  go-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - run: go version
      - run: |
          wget -qO yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x yq
      - run: ./yq --version
      - run: snap install yq
