name: pr
on:
  # but only for the main branch
  pull_request:
    branches:
      - master
jobs:
  pr-go-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - run: go version
      - run: |
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo $PR_NUMBER
      - run: echo $PR_NUMBER
