name: pr
on:
  # but only for the main branch
  pull_request:
    branches:
      - master

jobs:
  pr-go-version:
    runs-on: ubuntu-latest
    services:
      cloud_sql_proxy:
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        options: '/cloud_sql_proxy -instances=champs-dev-13804:asia-northeast1:champs-dev-postgre=tcp:0.0.0.0:5432'
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - run: go version
      # - run: |
      #     # docker run -d -ti --rm -p 127.0.0.1:5432:5432 gcr.io/cloudsql-docker/gce-proxy:1.16 /cloud_sql_proxy -instances=champs-dev-13804:asia-northeast1:champs-dev-postgre=tcp:0.0.0.0:5432
      #     export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
      #     echo $PR_NUMBER
      - run: echo 'sample' | grep nothing -c
      - run: echo $PR_NUMBER
