name: pr
on:
  # but only for the main branch
  pull_request:
    branches:
      - master
jobs:
  go-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - run: go version
